import dotenv from 'dotenv'


dotenv.config()

const { EMAIL_USER, EMAIL_PASSWORD, SECRET_KEY, MYSQL_HOST, MYSQL_DATABASE, MYSQL_USERNAME, MYSQL_PASSWORD, MONGO_DB_CONNECTION_STR, MONOGO_DB_DATABASE } = process.env

const ENVIROMENT = {
    EMAIL_USER: EMAIL_USER,
    EMAIL_PASSWORD: EMAIL_PASSWORD,
    SECRET_KEY: SECRET_KEY,
    MYSQL: {
        DATABASE: MYSQL_DATABASE,
        HOST: MYSQL_HOST,
        PASSWORD: MYSQL_PASSWORD,
        USERNAME: MYSQL_USERNAME
    },
    MONGO_DB_CONNECTION_STR: MONGO_DB_CONNECTION_STR,
    MONOGO_DB_DATABASE: MONOGO_DB_DATABASE

}

export default ENVIROMENT